#!/usr/bin/env bash
echo "🚨🚨 PRE-COMMIT HOOK RUNNING 🚨🚨"
# Run Flutter analyze and check for errors
echo "→ 👀🔎 Running Flutter analyze"
if ! output=$(flutter analyze); then
    echo "→ 🤔😭🤬 Found the following errors:"
    echo "$output"
    exit 1
fi
# Run Flutter Test and check for errors
echo "→ 👀🔎 Running Flutter Test"
if ! output=$(flutter test); then
    echo "→ 🤔😭🤬 Found the following errors:"
    echo "$output"
    exit 1
fi
# If we made it this far, the commit is allowed
echo "→ 🎉🥳❤️✅ No errors found!"
exit 0